export const ACCESS_SECRET = 'ACCESS_JWT_SECRET'
export const REFRESH_SECRET = 'REFRESH_JWT_SECRET'
export const REFRESH_TOKEN_COOKIE = 'refreshToken'
export const ACCESS_JWT_STRATEGY = 'access-jwt-strategy'
export const REFRESH_JWT_STRATEGY = 'refresh-jwt-strategy'